import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import web3 from "../components/web3";
import Asset from "../build/contracts/Asset.json";
import { useEffect, useState } from "react";

const asset = new web3.eth.Contract(
  Asset.abi as any,
  "0xCa1162DCACE6f29CBdcbA31978910eAbBd08C62F"
);

const Home: NextPage = () => {
  const [from, setFrom] = useState("");
  const [balance, setBalance] = useState(0);
  const [error, setError] = useState<any>("");
  const [tokenName, setTokenName] = useState("");

  const mint = async (uri: string) => {
    try {
      await asset.methods.mintAsset(uri).send({
        from: from,
      });
      setTokenName(await asset.methods.name().call());
    } catch (err) {
      setError(err);
    }
  };
  useEffect(() => {
    (async () => {
      const accounts = await web3.eth.getAccounts();
      setFrom(accounts[0]);

      const balance = await asset.methods.balanceOf(accounts[0]).call();
      setBalance(balance);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>NextFrame</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-lg px-6 py-4 bg-green-200 text-green-900 border-green-900 rounded-md">
          {from}
        </h1>
        <h1 className="text-lg px-6 py-4 bg-orange-200 text-orange-900 border-orange-900 rounded-md">
          {balance}
        </h1>
        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          onClick={() =>
            mint(
              "http://localhost:8080/ipfs/QmdxgWQMCq4D1ck7qyJvM1gxjnGsuz5FyuCmcZyiMUkTME"
            )
          }
        >
          {tokenName !== "" ? tokenName : "Mint"}
        </button>
      </main>
    </div>
  );
};

export default Home;
